### ISSUE TITLE
file permission error

### ISSUE THREAD

**Issue by bdolor** [FunnyMonkey/pressbooks#2]
export routine hung on a file permissions error. There was a .dat file in this directory that it said it couldn’t open:  /pressbooks/wp-content/plugins/pressbooks/symbionts/mpdf/ttfontdata

![screen shot 2015-02-03 at 1 19 34 pm](https://cloud.githubusercontent.com/assets/2048170/6085474/cef2a30e-adee-11e4-91db-61456c6c8d72.png)

I was able to work around this by modifying the permissions on the directory. Managing file/directory permissions with git is a likely/possible fix.

**Comment by jgraham909** [comment]
I don't want to adjust the existing permissions in the repo as those are already fairly permissive giving full access (read/write/execute) to owner and group with read and execute to 'other'.

Likely this should be a documentation issue to ensure that the directory is owned by either the web user or in a group the web user is a member of. For ubuntu systems this would be `www-data`.

I'm guessing the best place for this would be in Pressbook's top-level readme.txt under the section 'Part 3, PressBooks dependencies:' where we add instructions to ensure proper ownership of the files.

**Comment by jgraham909** [comment]
Additionally the following folders need to have write access;
- ttfontdata/ 
- tmp/ 
- graph_cache/
