### ISSUE TITLE
Add css option to inject css that would indent paragraphs

### ISSUE THREAD

**Issue by jgraham909** [FunnyMonkey/pressbooks#27]

**Comment by jgraham909** [comment]
I think this is unnecessary as it can either be addressed directly in custom themes or alternatively by implementing the pb_mpdf_css_override' filter, which accepts one parameter '$css', the css as calculated and to be sent to mdpf.

**Comment by bdolor** [comment]
The goal was to present the option to the user, regardless of which theme they've chosen which is similar to how it is currently presented with prince output. For instance, a function called `pressbooks_theme_mpdf_override($css)` located in `/pressbooks/themes-book/pressbooks-book/functions.php` would hook into the filter `pb_mpdf_css_override` and could check to see if a user has selected the indent paragraph option and add the css accordingly. The `pb_mpdf_css_override` filter would still be available to theme developers of course, but as a default the option would be available to all themes.

**Comment by jgraham909** [comment]
Thanks for the clarification Brad, I was trying to minimize functionality that should be delegated to theme developers to improve likelihood of upbranch merge into pressbooks. I had forgotten this was for parity with Prince.
