### ISSUE TITLE
TOC content and placement

### ISSUE THREAD

**Issue by bdolor** [FunnyMonkey/pressbooks#4]
The TOC needs to include listing/linking to front-matter and back-matter content. The placement of the TOC in the export file also needs to be prior to any front-matter content. Currently it is placed after front-matter content and prior to chapter content. 

Screenshot of pdf output with princeXML where Introduction (front-matter) and Appendix (back-matter) are listed/linked in TOC: 

![screen shot 2015-02-06 at 11 16 55 am](https://cloud.githubusercontent.com/assets/2048170/6085806/b775cf28-adf1-11e4-9e79-941addebad57.png)

**Comment by jgraham909** [comment]
Two things here;
1. TOC including listing & linking to front-matter & back-matter. This makes sense and I will get this implemented. 
2. Regarding placement; I see what you have requested is consistent with Prince's rendering. From a quick survey it seems that the phrasing "front matter" is inclusive of the Table of contents and that the following is the conventional ordering;
3. title page
4. copyright notices
5. abstract
6. Table of Contents 
7. the foreword
8. the preface

Pressbooks further confuses this issue by having some "front matter" duplicated in the "Book Info" information screen as well as in the specific front matter post types "
- Abstract
- Acknowledgements
- Before Title Page
- Chronology, Timeline
- Dedication
- Disclaimer
- Epigraph
- Forward
- Genealogy, Family Tree
- Image credits
- Introduction
- List of Abbreviations
- List of Characters
- List of Illustrations
- List of Tables
- Miscellaneous
- Other Books by Author
- Preface
- Prologue
- Recommended citation
- Title Page

In addition to the above the user can add arbitrary "front matter" types _and_ order those front matter portions in any specific order.

I suppose one approach would be to add all information derived from the "Book Information" settings screen as the pre TOC front matter and all user generated (via front matter post type ) is post table of contents in the order specified by the user followed by chapters and then back matter.

Thoughts?

**Comment by bdolor** [comment]
The most risk averse approach is to mimic the behaviour presented with the existing PDF output.  

`transform()` in `/pressbooks/includes/modules/export/xhtml/class-pb-xhtml.php` outlines an specific order and behaviour that users will have come to expect (see below). Deviating far from that would be hard for me to rationalize. At least, presenting different behaviour for outputs would require an explanation to users and become a support burden worth avoiding. 

![screen shot 2015-02-11 at 3 07 17 pm](https://cloud.githubusercontent.com/assets/2048170/6158495/b92645a2-b1ff-11e4-9d3b-d371278ce6a7.png)

The exceptional front-matter types that, if populated with content and marked for export, get shoved in front of the TOC are 'epigraph', 'dedication', 'title-page', 'before-title'. If that potentially duplicates data that currently exists in Book Info such as 'title', or 'title-page', I say, that's a burden we can safely pass on to the user (at least they are already used to it).

**Comment by jgraham909** [comment]
I guess what I find odd is straying from the content and ordering on the web. That said here is a functional breakdown of the above processes;
- echoMetaData(): Includes all book metadata.
- echoBeforeTitle(): Outputs front matter of type 'before-title'
- echoHalfTitle(): blog name
- echoCover(): Does nothing
- echoTitle(): Outputs front matter of type 'title-page'
- echoCopyright(): Includes additional metadata (repeats informaiton already output in echoMetaData
- echoDedicationAndEpigraph(): Outputs front matter of type 'dedication' and 'epigraph' respectively
- echoToC(): outputs TOC
- echoFrontMatter(): outputs all front matter skipping types: 'dedication', 'epigraph', 'title-page', 'before-title'
- createPromo(): gets output from apply_filters('pressbooks_pdf_promo', '');
- echoPartsAndChapters(): Outputs parts and then chapters.
- echoBackMatter(): Outputs backmatter.

Does the PDF output directly reflect that ordering? Is the cover really that far into the book?

Suggested output for mpdf;
1. Output the cover 
1. Output the front-matter of type 'before-title'
1. Output the front-matter of type 'title-page'
1. Output the existing book information page as currently implemented (a subset of the metadata including copyright information) this is essentially inclusive of; (echoHalfTitle(), echoTitle(), echoCopyright()
1. Output the front-matter of type 'dedication', 'epigraph'
1. Output the TOC
1. Output all front-matter not already output
1. Output parts and chapters
1. Output back-matter.
