### ISSUE TITLE
setCss and child themes

### ISSUE THREAD

**Issue by bdolor** [FunnyMonkey/pressbooks#6]
For themes that are child themes (i.e. most of the themes in PB); currently the stylesheet for the parent theme is excluded in [`setCss()`](https://github.com/FunnyMonkey/pressbooks/blob/dev/includes/modules/export/mpdf/class-pb-pdf.php#L390). If the parent theme css file was to be included prior to the child theme css file, the child theme rules would still, theoretically, override the parent theme rules. Including parent theme styles would  better represent the look and feel of the book.

**Comment by jgraham909** [comment]
Please take a look at the solution and see if that addresses your concerns. The wordpress API is a little sparse on what is the proper path in a situation like this.

**Comment by bdolor** [comment]
`getCssRecursive()` doesn't achieve the desired effect. Parent styles fail to return from this function. 

If you want the theme object returned, I believe it's `$theme->parent()`, not `$theme->parent` but then `$theme->get_template()` will be the faster way to get a string with the directory name. That said, I haven't looked into exactly what you're looking for so I don't know if this helps put you in the right direction.
